services:
  postgres:
    image: postgres:16-alpine
    container_name: devverse-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: devverse_db
    volumes:
      - ./backend/postgres-data:/var/lib/postgresql/data
    networks:
      - devverse-network

  adminer:
    image: adminer:latest
    container_name: devverse-adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres
    networks:
      - devverse-network

  frontend:
    build:
      context: ./devverse-front
      dockerfile: Dockerfile
    container_name: devverse-frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./devverse-front:/app
      - /app/node_modules 
    networks:
      - devverse-network

volumes:
  postgres-data:
    name: devverse-postgres-data

networks:
  devverse-network:
    name: devverse-network
